ALTER TABLE `client` ADD COLUMN `username` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `client` ADD COLUMN `first_name` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `client` ADD COLUMN `last_name` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `client` ADD COLUMN `keycloakId` VARCHAR(255) NOT NULL;