ALTER TABLE `booking`
ADD COLUMN `name` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `booking`
ADD COLUMN `email` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `booking`
ADD COLUMN `contact_no` VARCHAR(12) DEFAULT NULL;


ALTER TABLE `booking`
ADD COLUMN `additional_information` VARCHAR(5000) DEFAULT NULL;

ALTER TABLE `booking`
ADD COLUMN `address` VARCHAR(255) DEFAULT NULL;

